<?php

namespace Database\Seeders;

use App\Models\Recipe;
use Illuminate\Database\Seeder;

class RecipeSeeder extends Seeder
{
    public function run(): void
    {
        Recipe::create([
            'name' => 'Dal Bhat',
            'slug' => 'dal-bhat',
            'category' => 'Main Course',
            'description' => 'The most iconic Nepali dish - a wholesome combination of lentil curry served with steamed rice. A nutritious meal that\'s both humble and deeply satisfying.',
            'prep_time' => 15,
            'cook_time' => 45,
            'total_time' => 60,
            'servings' => 4,
            'difficulty' => 'Easy',
            'calories' => 320,
            'emoji' => '🍛',
            'featured' => true,
            'ingredients' => [
                ['item' => 'Red lentils (masuro dal)', 'quantity' => '1.5', 'unit' => 'cups'],
                ['item' => 'Water', 'quantity' => '4', 'unit' => 'cups'],
                ['item' => 'Turmeric powder', 'quantity' => '1', 'unit' => 'tsp'],
                ['item' => 'Cumin seeds', 'quantity' => '1', 'unit' => 'tsp'],
                ['item' => 'Ginger-garlic paste', 'quantity' => '2', 'unit' => 'tbsp'],
                ['item' => 'Green chilies', 'quantity' => '2', 'unit' => 'whole'],
                ['item' => 'Ghee (or oil)', 'quantity' => '3', 'unit' => 'tbsp'],
                ['item' => 'Cumin powder', 'quantity' => '0.5', 'unit' => 'tsp'],
                ['item' => 'Asafoetida (hing)', 'quantity' => 'a pinch', 'unit' => ''],
                ['item' => 'Salt', 'quantity' => 'to taste', 'unit' => ''],
                ['item' => 'Cilantro', 'quantity' => '2', 'unit' => 'tbsp'],
                ['item' => 'Rice', 'quantity' => '2', 'unit' => 'cups', 'uncooked'],
            ],
            'instructions' => [
                'Rinse the red lentils thoroughly under running water and drain completely.',
                'In a large pot, bring 4 cups of water to boil. Add lentils, turmeric powder, and salt.',
                'Reduce heat and simmer for 25-30 minutes until lentils are completely soft and begin to break down.',
                'In a separate pan, heat ghee and add cumin seeds. Let them crackle for 30 seconds.',
                'Add ginger-garlic paste and green chilies to the ghee. Sauté until fragrant (about 2 minutes).',
                'Pour the tempered ghee mixture into the cooked dal. Stir well and add asafoetida.',
                'Adjust salt and consistency by adding more water if needed. The dal should be thick but still pourable.',
                'Garnish with fresh cilantro and serve hot with steamed rice and vegetables.',
            ],
            'tips' => [
                'For creamier dal, blend half the cooked lentils before adding the tempering.',
                'Red lentils cook faster than other varieties, making dal preparation quick and easy.',
                'The tempering (tadka) of ghee and spices adds authentic flavor to the dal.',
                'Leftover dal can be refrigerated for up to 5 days and reheated for quick meals.',
                'Serve with achar (pickle) and gundruk (fermented vegetables) for authentic taste.',
            ],
        ]);

        Recipe::create([
            'name' => 'Momo (Steamed)',
            'slug' => 'momo-steamed',
            'category' => 'Snacks',
            'description' => 'Delicate steamed dumplings filled with spiced meat and vegetables. These beloved momos are softer and lighter than their fried counterparts, making them perfect for any occasion.',
            'prep_time' => 40,
            'cook_time' => 20,
            'total_time' => 60,
            'servings' => 6,
            'difficulty' => 'Medium',
            'calories' => 280,
            'emoji' => '🥟',
            'featured' => false,
            'ingredients' => [
                ['item' => 'All-purpose flour', 'quantity' => '2', 'unit' => 'cups'],
                ['item' => 'Water', 'quantity' => '0.75', 'unit' => 'cup'],
                ['item' => 'Salt', 'quantity' => '0.5', 'unit' => 'tsp'],
                ['item' => 'Ground meat (beef/buffalo)', 'quantity' => '1', 'unit' => 'lb'],
                ['item' => 'Onions (finely chopped)', 'quantity' => '1', 'unit' => 'medium'],
                ['item' => 'Ginger-garlic paste', 'quantity' => '2', 'unit' => 'tbsp'],
                ['item' => 'Green chilies (minced)', 'quantity' => '2', 'unit' => 'whole'],
                ['item' => 'Cilantro (chopped)', 'quantity' => '3', 'unit' => 'tbsp'],
                ['item' => 'Turmeric powder', 'quantity' => '0.5', 'unit' => 'tsp'],
                ['item' => 'Cumin powder', 'quantity' => '0.5', 'unit' => 'tsp'],
                ['item' => 'Black pepper', 'quantity' => '0.25', 'unit' => 'tsp'],
                ['item' => 'Oil', 'quantity' => '1', 'unit' => 'tbsp'],
                ['item' => 'Sesame oil', 'quantity' => '1', 'unit' => 'tsp'],
            ],
            'instructions' => [
                'Make the dough: Mix flour and salt. Add water gradually and knead until smooth. Cover and rest for 30 minutes.',
                'Prepare filling: Cook ground meat with onions until meat is brown and golden.',
                'Add ginger-garlic paste, green chilies, and turmeric to the meat. Cook for 2 minutes.',
                'Mix in cumin powder, black pepper, cilantro, and sesame oil. Let cool completely before using.',
                'Divide dough into plum-sized balls. Roll each ball into thin circle (2-3mm thick).',
                'Place 1 tablespoon of filling in the center of each wrapper. Fold into triangle, then bring corners together.',
                'Arrange momos on a steamer, leaving space between each one. Steam for 15-18 minutes until slightly translucent.',
                'Serve hot with sweet chili sauce, sesame oil, and chili flakes.',
            ],
            'tips' => [
                'Keep the dough moist but not sticky by adjusting water gradually.',
                'Half-cooked meat is easier to work with in the filling - it firms up as you prepare momos.',
                'For authentic taste, add finely chopped radish leaves or cabbage to the filling.',
                'Momos can be prepared in advance and frozen - steam directly from frozen.',
                'A steamer basket with water reduces sticking - brush lightly with oil.',
            ],
        ]);

        Recipe::create([
            'name' => 'Momo (Fried)',
            'slug' => 'momo-fried',
            'category' => 'Snacks',
            'description' => 'Crispy, golden-brown fried dumplings with a delightfully crunchy exterior. These momos are heavenly when served with spicy dipping sauce.',
            'prep_time' => 40,
            'cook_time' => 25,
            'total_time' => 65,
            'servings' => 6,
            'difficulty' => 'Medium',
            'calories' => 350,
            'emoji' => '🥟',
            'featured' => false,
            'ingredients' => [
                ['item' => 'All-purpose flour', 'quantity' => '2', 'unit' => 'cups'],
                ['item' => 'Water', 'quantity' => '0.75', 'unit' => 'cup'],
                ['item' => 'Salt', 'quantity' => '0.5', 'unit' => 'tsp'],
                ['item' => 'Ground meat (beef/buffalo)', 'quantity' => '1', 'unit' => 'lb'],
                ['item' => 'Onions (finely chopped)', 'quantity' => '1', 'unit' => 'medium'],
                ['item' => 'Ginger-garlic paste', 'quantity' => '2', 'unit' => 'tbsp'],
                ['item' => 'Green chilies (minced)', 'quantity' => '2', 'unit' => 'whole'],
                ['item' => 'Cilantro (chopped)', 'quantity' => '3', 'unit' => 'tbsp'],
                ['item' => 'Cumin powder', 'quantity' => '0.5', 'unit' => 'tsp'],
                ['item' => 'Oil for deep frying', 'quantity' => '2', 'unit' => 'cups'],
            ],
            'instructions' => [
                'Prepare dough exactly as for steamed momos and let rest for 30 minutes.',
                'Cook the meat filling following the same method as steamed momos.',
                'Roll and shape momos following the same technique.',
                'Heat oil to 350°F (175°C) in a deep pan. Test temperature by dropping a small piece of dough - it should sizzle immediately.',
                'Carefully place momos in hot oil, 3-4 at a time. Do not overcrowd the pan.',
                'Fry for 4-5 minutes, turning occasionally, until they become golden brown on all sides.',
                'Remove with a slotted spoon and drain on paper towels.',
                'Serve immediately while crispy with sweet chili sauce and vinegar-based dipping sauce.',
            ],
            'tips' => [
                'Keep oil temperature consistent - too cool and momos become greasy, too hot and they burn outside while staying raw inside.',
                'Fry in batches to maintain oil temperature and prevent momos from sticking together.',
                'For extra crispy momos, fry them once, rest for 5 minutes, then fry again for 2 minutes.',
                'Fried momos are best enjoyed immediately and don\'t store well.',
                'Use a meat thermometer - oil should be 325-350°F for perfect golden cooking.',
            ],
        ]);

        Recipe::create([
            'name' => 'Thakali Set',
            'slug' => 'thakali-set',
            'category' => 'Main Course',
            'description' => 'An elaborate traditional meal from the Thakali people of Nepal. This authentic set features dhido, gundruk, meat curry, and pickles representing the mountain cuisine at its finest.',
            'prep_time' => 30,
            'cook_time' => 60,
            'total_time' => 90,
            'servings' => 4,
            'difficulty' => 'Hard',
            'calories' => 520,
            'emoji' => '🍜',
            'featured' => false,
            'ingredients' => [
                ['item' => 'Cornmeal (makki ko piro)', 'quantity' => '1', 'unit' => 'cup'],
                ['item' => 'Buckwheat flour', 'quantity' => '0.5', 'unit' => 'cup'],
                ['item' => 'Water', 'quantity' => '3', 'unit' => 'cups'],
                ['item' => 'Ghee', 'quantity' => '4', 'unit' => 'tbsp'],
                ['item' => 'Gundruk (pickled vegetables)', 'quantity' => '1', 'unit' => 'cup'],
                ['item' => 'Beef/Buffalo meat', 'quantity' => '0.75', 'unit' => 'lb'],
                ['item' => 'Potatoes', 'quantity' => '3', 'unit' => 'medium'],
                ['item' => 'Onions', 'quantity' => '2', 'unit' => 'medium'],
                ['item' => 'Ginger-garlic paste', 'quantity' => '3', 'unit' => 'tbsp'],
                ['item' => 'Turmeric powder', 'quantity' => '1', 'unit' => 'tsp'],
                ['item' => 'Cumin powder', 'quantity' => '1', 'unit' => 'tsp'],
                ['item' => 'Coriander powder', 'quantity' => '0.5', 'unit' => 'tsp'],
                ['item' => 'Green chilies', 'quantity' => '4', 'unit' => 'whole'],
                ['item' => 'Cilantro', 'quantity' => '0.25', 'unit' => 'cup'],
                ['item' => 'Salt and pepper', 'quantity' => 'to taste', 'unit' => ''],
            ],
            'instructions' => [
                'Prepare meat curry: Cut meat into chunks. Heat 2 tbsp ghee in a large pot and brown the meat on high heat.',
                'Add onions and ginger-garlic paste. Sauté until onions are golden.',
                'Add turmeric, cumin, and coriander powders. Cook for 2 minutes.',
                'Add chopped potatoes, green chilies, and enough water to cover meat. Simmer for 45 minutes until meat is tender.',
                'Make Dhido: Bring 3 cups salted water to boil. Slowly add cornmeal, stirring constantly to avoid lumps.',
                'Add buckwheat flour gradually while stirring continuously. Cook for 15 minutes on medium heat, stirring frequently.',
                'Add remaining ghee to dhido and mix well. The consistency should be thick and moldable.',
                'Prepare gundruk curry: Sauté gundruk in 1 tbsp ghee for 3-4 minutes, then add to a bit of broth.',
                'Remove meat curry from heat and garnish with fresh cilantro.',
                'Serve hot: Place a mound of dhido in the center of plate, surround with meat curry and gundruk on the sides.',
            ],
            'tips' => [
                'Gundruk is a fermented vegetable that adds distinctive sour flavor - available in Nepali stores.',
                'Dhido must be stirred constantly to prevent lumps and burning at the bottom.',
                'The ratio of cornmeal to buckwheat flour can be adjusted based on preference.',
                'This meal is heavy and warming, perfect for cold mountain evenings.',
                'Traditionally served with fresh local pickles (achar) on the side.',
            ],
        ]);

        Recipe::create([
            'name' => 'Sel Roti',
            'slug' => 'sel-roti',
            'category' => 'Desserts',
            'description' => 'Sweet, spiral-shaped fried bread that\'s crispy on the outside and soft on the inside. A beloved traditional treat, especially during Diwali festival.',
            'prep_time' => 20,
            'cook_time' => 30,
            'total_time' => 50,
            'servings' => 10,
            'difficulty' => 'Medium',
            'calories' => 180,
            'emoji' => '🍪',
            'featured' => false,
            'ingredients' => [
                ['item' => 'Rice flour', 'quantity' => '1.5', 'unit' => 'cups'],
                ['item' => 'Semolina (sooji)', 'quantity' => '0.5', 'unit' => 'cup'],
                ['item' => 'Jaggery (gur)', 'quantity' => '0.75', 'unit' => 'cup', 'grated or finely crushed'],
                ['item' => 'Milk', 'quantity' => '0.75', 'unit' => 'cup'],
                ['item' => 'Ghee', 'quantity' => '3', 'unit' => 'tbsp'],
                ['item' => 'Cardamom powder', 'quantity' => '0.5', 'unit' => 'tsp'],
                ['item' => 'Ginger powder', 'quantity' => '0.25', 'unit' => 'tsp'],
                ['item' => 'Nutmeg powder', 'quantity' => 'a pinch', 'unit' => ''],
                ['item' => 'Sesame seeds', 'quantity' => '2', 'unit' => 'tbsp'],
                ['item' => 'Oil (for deep frying)', 'quantity' => '2', 'unit' => 'cups'],
                ['item' => 'Salt', 'quantity' => 'a pinch', 'unit' => ''],
            ],
            'instructions' => [
                'Mix rice flour and semolina in a large bowl. Add grated jaggery and mix well.',
                'Heat ghee and add to the flour mixture. Mix until the flour is crumbly and resembles breadcrumbs.',
                'Warm milk and add cardamom powder, ginger powder, and nutmeg powder to it.',
                'Gradually add milk to the flour mixture while mixing to form a thick, dough-like batter.',
                'Stir in sesame seeds and a pinch of salt. The batter should be thick enough to hold its shape.',
                'Heat oil to 350°F (175°C). Using a sel roti mold or pastry bag with large tip, pipe batter into oil in circular patterns.',
                'Fry until golden brown on the bottom (about 2-3 minutes), then carefully flip and fry the other side.',
                'Once fully golden, remove with a slotted spoon and drain on paper towels.',
                'Cool slightly. Sel roti becomes firmer as it cools.',
            ],
            'tips' => [
                'A traditional sel roti mold (circular mold with handle) creates the iconic spiral shape.',
                'If mold is not available, use a pastry bag with a large round tip.',
                'Make sure oil temperature is consistent - use a thermometer for best results.',
                'Jaggery imparts authentic flavor - white sugar won\'t provide the same richness.',
                'Sel roti stores well in an airtight container for up to 5 days and can be reheated to restore crispiness.',
            ],
        ]);

        Recipe::create([
            'name' => 'Newari Khaja Set',
            'slug' => 'newari-khaja-set',
            'category' => 'Snacks',
            'description' => 'A traditional Newari feast featuring multiple dishes including bara, beaten rice, spiced meat, and bamboo shoots. This elaborate set represents Newari culinary excellence.',
            'prep_time' => 50,
            'cook_time' => 90,
            'total_time' => 140,
            'servings' => 8,
            'difficulty' => 'Hard',
            'calories' => 420,
            'emoji' => '🍱',
            'featured' => false,
            'ingredients' => [
                ['item' => 'Black lentils (urad dal)', 'quantity' => '1', 'unit' => 'cup'],
                ['item' => 'Beaten rice (chiura)', 'quantity' => '2', 'unit' => 'cups'],
                ['item' => 'Beef/Buffalo meat', 'quantity' => '0.75', 'unit' => 'lb'],
                ['item' => 'Bamboo shoots (tama)', 'quantity' => '1', 'unit' => 'cup'],
                ['item' => 'Potatoes', 'quantity' => '2', 'unit' => 'medium'],
                ['item' => 'Onions', 'quantity' => '3', 'unit' => 'medium'],
                ['item' => 'Ginger-garlic paste', 'quantity' => '3', 'unit' => 'tbsp'],
                ['item' => 'Green chilies', 'quantity' => '5', 'unit' => 'whole'],
                ['item' => 'Turmeric powder', 'quantity' => '1', 'unit' => 'tsp'],
                ['item' => 'Cumin powder', 'quantity' => '1', 'unit' => 'tsp'],
                ['item' => 'Fenugreek leaves (methi)', 'quantity' => '0.25', 'unit' => 'cup'],
                ['item' => 'Oil', 'quantity' => '6', 'unit' => 'tbsp'],
                ['item' => 'Salt and pepper', 'quantity' => 'to taste', 'unit' => ''],
            ],
            'instructions' => [
                'Soak urad dal overnight. Next day, grind with water to make a smooth paste.',
                'Heat oil in a wok and drop spoonfuls of dal paste to fry into bara (fritters). Fry until golden on both sides. Set aside.',
                'Prepare meat curry: Heat 2 tbsp oil and brown meat chunks on high heat.',
                'Add onions and ginger-garlic paste. Sauté until onions turn golden.',
                'Add turmeric and cumin powders. Cook for 2 minutes.',
                'Add chopped potatoes, green chilies, and water. Simmer for 30 minutes until meat is tender.',
                'Prepare bamboo shoot curry: In another pan, sauté sliced tama (bamboo shoots) with remaining oil, onions, and spices for 15 minutes.',
                'Fry beaten rice (chiura) lightly in oil with cumin seeds and salt for 3-4 minutes.',
                'Assemble: Arrange fried bara, spiced meat curry, bamboo shoot curry, fried beaten rice, and fresh fenugreek leaves on a platter.',
                'Serve hot with fresh lemon juice and achar (pickle).',
            ],
            'tips' => [
                'Bara are lentil fritters that are crispy and absorb flavor from the curries beautifully.',
                'Tama (bamboo shoots) imparts a unique slightly sour taste - essential to Newari cooking.',
                'Each component can be prepared separately and assembled just before serving.',
                'This is a showstopper meal meant for special celebrations and gatherings.',
                'The combination of soft, crispy, spiced, and sour elements creates incredible flavor balance.',
            ],
        ]);

        Recipe::create([
            'name' => 'Chowmein',
            'slug' => 'chowmein',
            'category' => 'Main Course',
            'description' => 'Nepal\'s beloved street food and everyday meal - crispy stir-fried noodles with vegetables, eggs, and aromatic spices. Simple yet incredibly satisfying.',
            'prep_time' => 15,
            'cook_time' => 15,
            'total_time' => 30,
            'servings' => 4,
            'difficulty' => 'Easy',
            'calories' => 380,
            'emoji' => '🍝',
            'featured' => false,
            'ingredients' => [
                ['item' => 'Egg noodles', 'quantity' => '1', 'unit' => 'lb'],
                ['item' => 'Eggs', 'quantity' => '3', 'unit' => 'whole'],
                ['item' => 'Onions (thinly sliced)', 'quantity' => '1', 'unit' => 'large'],
                ['item' => 'Carrots (julienned)', 'quantity' => '1', 'unit' => 'medium'],
                ['item' => 'Cabbage (shredded)', 'quantity' => '2', 'unit' => 'cups'],
                ['item' => 'Green beans', 'quantity' => '0.5', 'unit' => 'cup'],
                ['item' => 'Green chilies (minced)', 'quantity' => '2', 'unit' => 'whole'],
                ['item' => 'Ginger-garlic paste', 'quantity' => '1', 'unit' => 'tbsp'],
                ['item' => 'Cumin seeds', 'quantity' => '1', 'unit' => 'tsp'],
                ['item' => 'Soy sauce', 'quantity' => '2', 'unit' => 'tbsp'],
                ['item' => 'Sesame oil', 'quantity' => '1', 'unit' => 'tbsp'],
                ['item' => 'Oil', 'quantity' => '3', 'unit' => 'tbsp'],
                ['item' => 'Cilantro', 'quantity' => '2', 'unit' => 'tbsp'],
                ['item' => 'Salt and pepper', 'quantity' => 'to taste', 'unit' => ''],
            ],
            'instructions' => [
                'Boil noodles in a large pot of salted water until just tender. Drain and rinse with cold water. Toss with 1 tbsp oil to prevent sticking.',
                'Heat 1 tbsp oil in a wok or large pan on high heat. Scramble eggs until cooked through. Remove and set aside.',
                'In the same wok, heat remaining 2 tbsp oil. Add cumin seeds and let them crackle.',
                'Add ginger-garlic paste and onions. Stir-fry for 2 minutes until onions are softened.',
                'Add carrots, cabbage, green beans, and green chilies. Stir-fry for 3-4 minutes until vegetables are tender-crisp.',
                'Add cooked noodles to the wok and mix well with vegetables.',
                'Pour soy sauce and sesame oil over the noodles. Toss everything together for 2-3 minutes.',
                'Return scrambled eggs to the wok and gently fold in.',
                'Season with salt and pepper to taste. Garnish with fresh cilantro.',
                'Serve immediately while hot and crispy.',
            ],
            'tips' => [
                'The key to great chowmein is high heat and quick cooking - don\'t overcook the noodles.',
                'Pre-cut all vegetables before you start cooking as the actual cooking is very quick.',
                'Keep noodles slightly undercooked as they continue cooking in the wok.',
                'Toss noodles constantly to achieve the desirable crispy edges.',
                'Adjust soy sauce and sesame oil to personal taste - this is very customizable.',
            ],
        ]);

        Recipe::create([
            'name' => 'Gundruk Soup',
            'slug' => 'gundruk-soup',
            'category' => 'Main Course',
            'description' => 'A warming, tangy soup made from fermented and dried greens. Rich in probiotics and flavor, this traditional Nepali comfort food is healthy and delicious.',
            'prep_time' => 10,
            'cook_time' => 40,
            'total_time' => 50,
            'servings' => 4,
            'difficulty' => 'Easy',
            'calories' => 140,
            'emoji' => '🥣',
            'featured' => false,
            'ingredients' => [
                ['item' => 'Gundruk (fermented vegetables)', 'quantity' => '1.5', 'unit' => 'cups'],
                ['item' => 'Potatoes (medium)', 'quantity' => '2', 'unit' => 'whole'],
                ['item' => 'Onions', 'quantity' => '1', 'unit' => 'medium'],
                ['item' => 'Ginger (sliced)', 'quantity' => '1', 'unit' => 'tbsp'],
                ['item' => 'Garlic cloves', 'quantity' => '4', 'unit' => 'whole'],
                ['item' => 'Green chilies', 'quantity' => '2', 'unit' => 'whole'],
                ['item' => 'Beans (fresh)', 'quantity' => '0.5', 'unit' => 'cup'],
                ['item' => 'Vegetable or chicken broth', 'quantity' => '6', 'unit' => 'cups'],
                ['item' => 'Ghee', 'quantity' => '2', 'unit' => 'tbsp'],
                ['item' => 'Cumin seeds', 'quantity' => '0.5', 'unit' => 'tsp'],
                ['item' => 'Turmeric powder', 'quantity' => '0.25', 'unit' => 'tsp'],
                ['item' => 'Salt and pepper', 'quantity' => 'to taste', 'unit' => ''],
                ['item' => 'Cilantro', 'quantity' => '2', 'unit' => 'tbsp'],
            ],
            'instructions' => [
                'Chop gundruk into small pieces. If it\'s very salty, rinse gently under water.',
                'Peel and cube potatoes. Slice onions and crush garlic.',
                'Heat ghee in a large pot and add cumin seeds. Let them crackle for 30 seconds.',
                'Add sliced onions and cook until soft. Add crushed garlic and sliced ginger.',
                'Add turmeric powder and mix well.',
                'Pour in the broth and bring to a boil.',
                'Add potatoes, green chilies, and fresh beans. Simmer for 15 minutes until vegetables are nearly cooked.',
                'Add gundruk and continue simmering for 10-15 minutes for flavors to meld.',
                'Season with salt and pepper to taste. The gundruk will add its own sourness.',
                'Garnish with fresh cilantro and serve hot.',
            ],
            'tips' => [
                'Gundruk is fermented, so it adds probiotics and authentic sour taste to the soup.',
                'Too much gundruk can overpower the soup - start with 1 cup and adjust to taste.',
                'This soup tastes even better the next day as flavors meld and develop.',
                'Can be made vegetarian by using vegetable broth instead of chicken broth.',
                'Leftovers store well in the refrigerator for up to 4 days.',
            ],
        ]);

        Recipe::create([
            'name' => 'Dhido',
            'slug' => 'dhido',
            'category' => 'Main Course',
            'description' => 'A traditional mountain staple - thick, smooth polenta-like dish made from cornmeal and buckwheat. Hearty and filling, often served with curries and pickles.',
            'prep_time' => 5,
            'cook_time' => 25,
            'total_time' => 30,
            'servings' => 4,
            'difficulty' => 'Easy',
            'calories' => 240,
            'emoji' => '🥖',
            'featured' => false,
            'ingredients' => [
                ['item' => 'Cornmeal (makki ko piro)', 'quantity' => '1.5', 'unit' => 'cups'],
                ['item' => 'Buckwheat flour (phapar)', 'quantity' => '0.75', 'unit' => 'cup'],
                ['item' => 'Water', 'quantity' => '4', 'unit' => 'cups'],
                ['item' => 'Ghee', 'quantity' => '4', 'unit' => 'tbsp'],
                ['item' => 'Salt', 'quantity' => '1', 'unit' => 'tsp'],
                ['item' => 'Black pepper', 'quantity' => '0.5', 'unit' => 'tsp'],
                ['item' => 'Onion (optional)', 'quantity' => '0.5', 'unit' => 'medium'],
            ],
            'instructions' => [
                'In a large, heavy-bottomed pot, bring 4 cups of water to a rolling boil.',
                'Add salt to the boiling water.',
                'Slowly sprinkle cornmeal into boiling water while stirring constantly with a wooden spoon to avoid lumps.',
                'Continue stirring as the mixture becomes thick and lumpy.',
                'Gradually add buckwheat flour, continuing to stir constantly.',
                'Reduce heat to medium-low and keep stirring for 15-20 minutes until the mixture becomes smooth, thick, and pulls away from the sides of the pot.',
                'Add ghee and black pepper, mixing thoroughly.',
                'The dhido should have a thick, moldable consistency - adjust the thickness by adding water if needed.',
                'Transfer to a serving plate. Traditionally, it\'s molded into a dome or thick round shape.',
            ],
            'tips' => [
                'Constant stirring is essential to prevent lumps and burning at the bottom.',
                'The ratio of cornmeal to buckwheat can be adjusted - more buckwheat makes it tangier.',
                'Dhido is best served immediately while hot and soft.',
                'Traditionally accompanied by meat curry, gundruk, and spiced pickles.',
                'Water temperature affects cooking time - use very hot water and high heat to start',
            ],
        ]);

        Recipe::create([
            'name' => 'Aloo Tama',
            'slug' => 'aloo-tama',
            'category' => 'Main Course',
            'description' => 'A classic Nepali curry featuring tender potatoes and bamboo shoots in aromatic spiced gravy. This comfort food is light yet deeply satisfying.',
            'prep_time' => 15,
            'cook_time' => 35,
            'total_time' => 50,
            'servings' => 4,
            'difficulty' => 'Easy',
            'calories' => 180,
            'emoji' => '🍲',
            'featured' => false,
            'ingredients' => [
                ['item' => 'Potatoes (medium)', 'quantity' => '4', 'unit' => 'whole'],
                ['item' => 'Bamboo shoots (tama)', 'quantity' => '2', 'unit' => 'cups'],
                ['item' => 'Onions', 'quantity' => '1', 'unit' => 'large'],
                ['item' => 'Garlic cloves', 'quantity' => '6', 'unit' => 'whole'],
                ['item' => 'Green chilies', 'quantity' => '3', 'unit' => 'whole'],
                ['item' => 'Ginger (sliced)', 'quantity' => '1', 'unit' => 'tbsp'],
                ['item' => 'Turmeric powder', 'quantity' => '0.75', 'unit' => 'tsp'],
                ['item' => 'Cumin powder', 'quantity' => '0.5', 'unit' => 'tsp'],
                ['item' => 'Coriander powder', 'quantity' => '0.5', 'unit' => 'tsp'],
                ['item' => 'Oil', 'quantity' => '3', 'unit' => 'tbsp'],
                ['item' => 'Water', 'quantity' => '2', 'unit' => 'cups'],
                ['item' => 'Salt and pepper', 'quantity' => 'to taste', 'unit' => ''],
                ['item' => 'Cilantro', 'quantity' => '3', 'unit' => 'tbsp'],
            ],
            'instructions' => [
                'Peel and cut potatoes into 1-inch cubes.',
                'Cut bamboo shoots into similar-sized pieces. Slice onions and crush garlic.',
                'Heat oil in a large pot over medium-high heat.',
                'Add cumin powder and let it crackle for 30 seconds.',
                'Add sliced onions and cook until translucent, about 2 minutes.',
                'Add crushed garlic, sliced ginger, and green chilies. Cook for another minute until fragrant.',
                'Add turmeric and coriander powders. Stir well and cook for 1 minute.',
                'Add cubed potatoes and stir to coat with spices.',
                'Add 2 cups water and salt. Bring to a boil, then reduce heat and simmer for 15 minutes.',
                'Add bamboo shoots and continue simmering for 10-12 minutes until potatoes are completely tender.',
                'Taste and adjust seasonings. The dish should be slightly thick in broth.',
                'Garnish with fresh cilantro and serve hot with rice or dhido.',
            ],
            'tips' => [
                'Bamboo shoots add a unique slightly sour and tender texture to the curry.',
                'Don\'t overboil potatoes as they can become mushy.',
                'The slight sourness from tama balances the earthy potatoes perfectly.',
                'This curry tastes better the next day as flavors develop.',
                'Pairs beautifully with jeera rice and fresh pickles.',
            ],
        ]);

        Recipe::create([
            'name' => 'Yomari',
            'slug' => 'yomari',
            'category' => 'Desserts',
            'description' => 'Delicate rice flour dumplings filled with sweet jaggery and crushed sesame seeds. These beloved treats are especially popular during Yomari Punhi festival.',
            'prep_time' => 30,
            'cook_time' => 20,
            'total_time' => 50,
            'servings' => 12,
            'difficulty' => 'Medium',
            'calories' => 120,
            'emoji' => '🍡',
            'featured' => false,
            'ingredients' => [
                ['item' => 'Rice flour', 'quantity' => '2', 'unit' => 'cups'],
                ['item' => 'Water (warm)', 'quantity' => '0.75', 'unit' => 'cup'],
                ['item' => 'Salt', 'quantity' => 'a pinch', 'unit' => ''],
                ['item' => 'Jaggery (gur)', 'quantity' => '0.75', 'unit' => 'cup', 'grated'],
                ['item' => 'Sesame seeds', 'quantity' => '0.5', 'unit' => 'cup'],
                ['item' => 'Ghee', 'quantity' => '2', 'unit' => 'tbsp'],
                ['item' => 'Cardamom powder', 'quantity' => '0.25', 'unit' => 'tsp'],
                ['item' => 'Ginger powder', 'quantity' => 'a pinch', 'unit' => ''],
                ['item' => 'Water (for cooking)', 'quantity' => '6', 'unit' => 'cups'],
            ],
            'instructions' => [
                'In a bowl, mix rice flour with a pinch of salt.',
                'Gradually add warm water and knead into a soft, smooth dough. Cover and let rest for 10 minutes.',
                'Prepare filling: Dry roast sesame seeds in a pan for 2-3 minutes until fragrant. Crush lightly.',
                'Mix crushed sesame seeds with grated jaggery, cardamom powder, and ginger powder.',
                'Divide dough into 12 equal portions and roll into balls.',
                'Flatten each ball into a small disc. Place 1 tbsp of filling in the center.',
                'Bring edges together to seal and mold into a traditional teardrop or oval shape.',
                'Bring 6 cups of water to a boil in a large pot.',
                'Carefully place yomari into boiling water. They will sink initially but float to the surface when cooked.',
                'Once they float, cook for 2-3 minutes more. Remove with a slotted spoon.',
                'Transfer to a bowl and drizzle with melted ghee. Serve warm.',
            ],
            'tips' => [
                'The traditional teardrop shape is achieved by gently shaping the dough while sealing the filling inside.',
                'Warm water makes the dough easier to work with and smoother.',
                'Jaggery provides authentic flavor - avoid substituting with white sugar.',
                'Yomari should float when cooked - if they sink, the dough is too dense.',
                'These can be made ahead and reheated by gently warming in ghee before serving.',
            ],
        ]);

        Recipe::create([
            'name' => 'Masu Bhaatw',
            'slug' => 'masu-bhaatw',
            'category' => 'Main Course',
            'description' => 'A hearty Nepali-style meat curry served with steamed rice. Masu Bhaatw is rich, aromatic, and perfect for family meals and special gatherings.',
            'prep_time' => 20,
            'cook_time' => 55,
            'total_time' => 75,
            'servings' => 4,
            'difficulty' => 'Medium',
            'calories' => 490,
            'emoji' => '🍖',
            'featured' => false,
            'ingredients' => [
                ['item' => 'Goat meat (bone-in)', 'quantity' => '1', 'unit' => 'kg'],
                ['item' => 'Rice', 'quantity' => '2', 'unit' => 'cups'],
                ['item' => 'Onions (sliced)', 'quantity' => '2', 'unit' => 'large'],
                ['item' => 'Tomatoes (chopped)', 'quantity' => '2', 'unit' => 'medium'],
                ['item' => 'Ginger-garlic paste', 'quantity' => '2', 'unit' => 'tbsp'],
                ['item' => 'Mustard oil', 'quantity' => '4', 'unit' => 'tbsp'],
                ['item' => 'Turmeric powder', 'quantity' => '1', 'unit' => 'tsp'],
                ['item' => 'Cumin powder', 'quantity' => '1', 'unit' => 'tsp'],
                ['item' => 'Coriander powder', 'quantity' => '1', 'unit' => 'tsp'],
                ['item' => 'Red chili powder', 'quantity' => '0.5', 'unit' => 'tsp'],
                ['item' => 'Garam masala', 'quantity' => '0.5', 'unit' => 'tsp'],
                ['item' => 'Green chilies', 'quantity' => '2', 'unit' => 'whole'],
                ['item' => 'Fresh cilantro', 'quantity' => '0.25', 'unit' => 'cup'],
                ['item' => 'Salt', 'quantity' => 'to taste', 'unit' => ''],
                ['item' => 'Water', 'quantity' => '3', 'unit' => 'cups'],
            ],
            'instructions' => [
                'Rinse the goat meat and drain thoroughly. Marinate with turmeric, salt, and half the ginger-garlic paste for 20 minutes.',
                'Heat mustard oil in a heavy pot until it starts to smoke lightly, then reduce heat.',
                'Add sliced onions and cook until deep golden brown.',
                'Stir in the remaining ginger-garlic paste and cook for 1 minute until fragrant.',
                'Add chopped tomatoes, cumin powder, coriander powder, and red chili powder. Cook until tomatoes break down and oil separates.',
                'Add marinated meat and sauté on medium-high heat for 8-10 minutes to seal in flavor.',
                'Pour in water, add green chilies, cover, and simmer for 35-40 minutes until the meat is tender.',
                'Sprinkle garam masala and adjust salt. Simmer uncovered for 5 minutes to thicken the gravy.',
                'Garnish with fresh cilantro and rest the curry for 5 minutes before serving.',
                'Serve hot with steamed rice for a classic Masu Bhaatw meal.',
            ],
            'tips' => [
                'Bone-in goat meat gives the curry deeper flavor and richer stock.',
                'Slow simmering is key for tender meat and balanced spices.',
                'If the gravy gets too thick, add a little hot water while cooking.',
                'Mustard oil adds authentic Nepali flavor; neutral oil can be used if needed.',
                'Masu tastes even better the next day after the spices settle.',
            ],
        ]);
    }
}
